Repository smart-village-solutions/smart-village-app-cms, pull requests merged in 2021-07, with the labels that each got.

#69 CMS Bereiche überarbeiten
  app/assets/stylesheets/custom.css
  app/views/dashboard/index.html.erb
  app/views/events/index.html.erb
  app/views/news_items/_form.html.erb
  app/views/news_items/index.html.erb
  app/views/point_of_interests/_form.html.erb
  app/views/point_of_interests/form_partials/_lunch_offers_form.html.erb
  app/views/point_of_interests/form_partials/_lunches_form.html.erb
  app/views/point_of_interests/index.html.erb
  app/views/shared/partials/_categories_form.html.erb
  app/views/shared/partials/_contacts_form.html.erb
  app/views/shared/partials/_content_blocks_form.html.erb
  app/views/shared/partials/_media_contents_form.html.erb
  app/views/shared/partials/_opening_hours_form.html.erb
  app/views/shared/partials/_price_informations_form.html.erb
  app/views/shared/partials/_url_form.html.erb
  app/views/shared/partials/_web_url_form.html.erb
  app/views/tours/_form.html.erb
  app/views/tours/index.html.erb
  app/views/waste_calendar/index.html.erb
Labels: enhancement

#80 Fix errors on data handling
  app/services/converter/base.rb
  app/views/shared/partials/_dates_form.html.erb
Labels: bug

#81 Hide initial sections in forms
  app/controllers/events_controller.rb
  app/controllers/point_of_interests_controller.rb
  app/helpers/form_helper.rb
  app/javascript/partials/_nested_content_block_form.js
  app/javascript/partials/_nested_forms.js
  app/javascript/partials/_nested_lunch_form.js
  app/views/jobs/_form.html.erb
  app/views/jobs/form_partials/_job_content.html.erb
  app/views/offers/_form.html.erb
  app/views/point_of_interests/form_partials/_lunch_offers_form.html.erb
  app/views/point_of_interests/form_partials/_lunches_form.html.erb
  app/views/shared/partials/_contact_form.html.erb
  app/views/shared/partials/_contacts_form.html.erb
  app/views/shared/partials/_content_blocks_form.html.erb
  app/views/shared/partials/_dates_form.html.erb
  app/views/shared/partials/_media_contents_form.html.erb
  app/views/shared/partials/_opening_hours_form.html.erb
  app/views/shared/partials/_price_informations_form.html.erb
  app/views/shared/partials/_url_form.html.erb
  app/views/shared/partials/_web_url_form.html.erb
Labels: enhancement

#78 Comments for surveys
  app/controllers/data_provider_controller.rb
  app/controllers/survey_comments_controller.rb
  app/controllers/surveys_controller.rb
  app/helpers/application_helper.rb
  app/views/layouts/_sidebar_navigation.html.erb
  app/views/survey_comments/_modal_message.html.erb
  app/views/survey_comments/index.html.erb
  app/views/surveys/index.html.erb
  config/routes.rb
Labels: enhancement

#76 Epic/survey
  app/controllers/data_provider_controller.rb
  app/controllers/survey_comments_controller.rb
  app/controllers/surveys_controller.rb
  app/helpers/application_helper.rb
  app/helpers/i18n_helper.rb
  app/services/converter/base.rb
  app/views/layouts/_sidebar_navigation.html.erb
  app/views/shared/partials/_dates_form.html.erb
  app/views/survey_comments/_modal_message.html.erb
  app/views/survey_comments/index.html.erb
  app/views/surveys/_form.html.erb
  app/views/surveys/edit.html.erb
  app/views/surveys/form_partials/_response_options_form.html.erb
  app/views/surveys/index.html.erb
  app/views/surveys/new.html.erb
  config/routes.rb
Labels: epic

#93 fix(date fields): force visibility for all date fields
  app/views/constructions/_form.html.erb
  app/views/jobs/_form.html.erb
  app/views/offers/_form.html.erb
  app/views/surveys/_form.html.erb
Labels: bug

#94 feat(constructions): update form fields
  app/controllers/constructions_controller.rb
  app/views/constructions/_form.html.erb
  app/views/shared/partials/_restrictions_form.html.erb
Labels: enhancement

#95 feat: add dates to index views
  app/controllers/constructions_controller.rb
  app/controllers/jobs_controller.rb
  app/controllers/offers_controller.rb
  app/controllers/surveys_controller.rb
  app/views/constructions/index.html.erb
  app/views/jobs/index.html.erb
  app/views/offers/index.html.erb
  app/views/surveys/index.html.erb
Labels: enhancement

#96 CMS Button + Date cell Changes
  app/assets/stylesheets/custom.css
  app/views/constructions/index.html.erb
  app/views/events/index.html.erb
  app/views/jobs/index.html.erb
  app/views/news_items/index.html.erb
  app/views/offers/index.html.erb
  app/views/point_of_interests/index.html.erb
  app/views/surveys/index.html.erb
  app/views/tours/index.html.erb
  app/views/waste_calendar/index.html.erb
Labels: enhancement

#97 Better initial forms
  app/controllers/constructions_controller.rb
  app/controllers/events_controller.rb
  app/controllers/news_items_controller.rb
  app/controllers/point_of_interests_controller.rb
  app/controllers/tours_controller.rb
  app/helpers/form_helper.rb
  app/javascript/partials/_nested_content_block_form.js
  app/javascript/partials/_nested_forms.js
  app/javascript/partials/_nested_lunch_form.js
  app/views/point_of_interests/_form.html.erb
  app/views/point_of_interests/form_partials/_attributes_form.html.erb
  app/views/point_of_interests/form_partials/_lunches_form.html.erb
  app/views/shared/partials/_categories_form.html.erb
  app/views/shared/partials/_media_contents_form.html.erb
Labels: bug, enhancement
